import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./fonts/fonts.css"
import Fonts from "./fonts/Fonts";
import NavBar from "./components/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const bungeeTintRegular = "bungee-tint-regular";

export const metadata: Metadata = {
  title: "NEXT JS DEMO APP / ROOT",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Fonts />
      </head>
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
            <NavBar/>
        <div className="container mx-10 mt-10 px-4 fade-in">
        {children}
        </div>
      </body>
    </html>
  );
}
